TOKEN = 'DISCORD_BOT_TOKEN'
VIRUSTOTAL_API_KEY = 'VIRUSTOTAL_API_KEY'
URLSCAN_API_KEY = 'URLSCAN_API_KEY'
guild_ids = [YOUR_GUILD_ID]
SCAN_CHANNEL_ID = CHANNEL_ID_WHERE_AUTO_SCANS_GO
ALLOWED_ROLE_IDS = [MOD_ROLE_ID_HERE]
MAX_URL_LENGTH = 2000